server:
  world:
    tick_per_second: 30
walls_path_dev: "web/data/ship_wall_colliders_v3.json"
walls_path: "web/dist/data/ship_wall_colliders_v3.json"
doors_path_dev: "web/data/ship_door_colliders_v3.json"
doors_path: "web/dist/data/ship_door_colliders_v3.json"
rooms_path_dev: "web/data/ship_room_colliders_v3.json"
rooms_path: "web/dist/data/ship_room_colliders_v3.json"

alien_spawns: 
  - x: 3 
    z: -1



